name: Release
on:
  release:
    types: [published]

jobs:
  release:
    name: Release to Maven Plugins
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Deploy Plugin
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.gradle_publish_key }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.gradle_publish_secret }}
        run: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET --no-daemon
